language: node_js
node_js:
  - "6.9.1"
before_install:
  - git clone https://github.com/kodeklubben/oppgaver.git ../oppgaver
script:
  - yarn run eslint
  - yarn run stylelint
  - yarn run test
  - ./travis_build_prod.sh
